### ISSUE TITLE
Release the new user interface 

### ISSUE THREAD

**Issue by igarousi** [I-GUIDE/catalog#103]
Collaborators at USU will work on this. Updates include the new interface of the data catalog, mainly the landing page of the submitted items.

#JIRA=CAM-54

**Comment by Castronova** [comment]
related to https://github.com/I-GUIDE/catalogapi/issues/87

**Comment by Maurier** [comment]
As part of this work, we are updating our front-end software stack to Vue 3.


- [x] Migrate to Vue 3.
    - [x] Initial project configuration.
      - [x] Integrate Vue Router v4 (https://router.vuejs.org/guide/).
      - [x] Update route guards.
      - [x] Configure Vite (https://vitejs.dev/guide/).
    - [x] Follow instructions in migration guide (https://v3-migration.vuejs.org/).
    - [x] Replace 'vue-property-decorator' with 'vue-facing-decorator' (https://facing-dev.github.io/vue-facing-decorator/#/). 
    - [x] Fix build error: https://github.com/I-GUIDE/catalogapi/pull/127#issuecomment-2090810017
- [x] Follow upgrade guide to update to Vuetify 3 (https://vuetifyjs.com/en/getting-started/upgrade-guide/#setup).
- [x] Fix theme inconsistencies resulting from migrations above.
- [x] cznet-vue-core migration.
  - [x] Migrate to Vue 3.
  - [x] Update every renderer with new Vuetify 3 components APIs. Follow upgrade guide (https://vuetifyjs.com/en/getting-started/upgrade-guide/#setup).
  - [x] Replace rollup with Vite, debug build and publish to NPM.
  - [x] Find alternatives for missing components in Vuetify 3.
- [x] Debug renderers integration in iGuide and update JSONSchema to new specifications.
- [x] Migrate new landing page implementation to Vue 3 app.

**Comment by horsburgh** [comment]
Deployed to production. Closing.
