### ISSUE TITLE
Deploy S3 registration API endpoints

### ISSUE THREAD

**Issue by Castronova** [I-GUIDE/catalog#117]
Deploy the API endpoints for registering S3 data in the catalog to production.

**Comment by horsburgh** [comment]
@pkdash can this be closed?

**Comment by pkdash** [comment]
@horsburgh I am not sure. The API endpoints for registering S3 dataset has been deployed with limited functionality. As you know currently these endpoints (the ones exposed to the UI) are not accessing any S3 storage. Maybe we can close this for now and add new issues/features for S3 dataset registration when we have bit more feature requirements along with storage authentication/authorization figured out.

**Comment by horsburgh** [comment]
OK. I'm going to close this for now in favor of specifying more specific issues for subsequent releases.
