### ISSUE TITLE
Add resource-level metadata to MongoDB

### ISSUE THREAD

**Issue by Castronova** [I-GUIDE/catalog#119]
Add support for resource-level metadata to be saved in MongoDB.

**Comment by pkdash** [comment]
@Castronova Currently resource level metadata gets saved to the catalog when a Hydroshare resource is registered using the resource url. Is this issue a different requirement?

**Comment by Castronova** [comment]
@pkdash This ticket was created from one of our action items in the last meeting. It's entirely possible that I didn't capture the issue correctly, or that it's already been implemented. Perhaps @sblack-usu has some additional insight?

**Comment by horsburgh** [comment]
I don't see any additional discussion on this issue, and since resource level metadata can be saved to the catalog for all use cases we have implemented so far, I'm closing this issue.
