### ISSUE TITLE
Archive the data-catalog repository

### ISSUE THREAD

**Issue by Castronova** [I-GUIDE/catalog#123]
Archive the data-catalog repository and rename catalogapi.

**Comment by horsburgh** [comment]
@Castronova - any objections to me archiving the data-catalog repo and then renaming the catalogapi repo? I would like to close this issue out. We decided not to rename the catalogapi repo until after the release got pushed out.

**Comment by Castronova** [comment]
@horsburgh No objections.

**Comment by Castronova** [comment]
However, we should update the readme file prior to archiving the repo to indicate that our code has moved.

**Comment by Castronova** [comment]
I see that you've already updated the readme, so I just archived the old repo. Closing.
