### ISSUE TITLE
Limit search results using a minimum score threshold

### ISSUE THREAD

**Issue by Maurier** [I-GUIDE/catalog#134]
Since our search results UI provides infinite scrolling, we need a way to stop showing results once they are no longer relevant as the user scrolls down. One way to do it is to add a limiter to our aggregation pipeline that uses the result scores.

**Comment by Maurier** [comment]
This has been implemented. We've set a minimum score based on observations. We'll monitor the accuracy of results and adjust if necessary.

**Comment by pkdash** [comment]
@Maurier I think we should close this issue for now.
