### ISSUE TITLE
How to cite element uses weird text wrapping

### ISSUE THREAD

**Issue by horsburgh** [I-GUIDE/catalog#144]
In the "How to Cite" section of the new landing page, the text is not wrapping full words - it's splitting words across lines:

<img width="336" alt="image" src="https://github.com/I-GUIDE/catalogapi/assets/3485902/0927a5c7-bdbc-4d06-957e-6478f328cc69">

**Comment by horsburgh** [comment]
@Maurier - can this be closed?

**Comment by Maurier** [comment]
Yes, this has been fixed. Closing.
