### ISSUE TITLE
URLs to files in HydroShare resources do not work

### ISSUE THREAD

**Issue by horsburgh** [I-GUIDE/catalog#147]
When I register a HydroShare resource with the catalog, I see the list of files within the resource in the file browser on the Catalog's resource landing page. I can right click on a file and select "View Metadata", which shows me a modal form with the "Content URL" and "Encoding Format". The URL shows up as a link, but when I click on it, nothing happens. As a user, I would expect that the link would provide access to download the file. 

<img width="1032" alt="image" src="https://github.com/I-GUIDE/catalog/assets/3485902/9ba9f15d-7e0b-4f23-8c4a-5dd021375c5d">

**Comment by Maurier** [comment]
I tried this with another resource and it looks like the browser is blocking the request for security reasons. I'll see if there is a workaround.
![image](https://github.com/I-GUIDE/catalog/assets/2448568/52bafd43-7944-4b47-ba3e-ab47e83093ea)

@horsburgh - It seems that these URLs are not landing pages for the files, bur rather download links. Do we want to indicate so?

**Comment by horsburgh** [comment]
@Maurier - correct, these are links to download individual files. I don't think we need to change the modal form because "Content URL" I think is descriptive that it is a URL to the content file. But, it would be good if the link worked to download the file. 

There is some risk I suppose because those files could be large and downloading may take some time. Do we have information in the file level metadata about the size of the file that you could also put on that modal so  a user would know how large the file is before they try to download?

**Comment by Maurier** [comment]
Yes, we are displaying this information below the file name, see the screenshot above.

**Comment by Maurier** [comment]
This has been fixed by making sure that the content is downloaded over https.
