### ISSUE TITLE
Turn off scheduled refresh of S3 dataset metadata

### ISSUE THREAD

**Issue by pkdash** [I-GUIDE/catalog#156]
Current implementation of the scheduler tries to refresh metadata for registered datasets similar to the hydroshare datasets/resources. Since we have not yet established the rules for accessing S3 storage, the scheduler obviously fails when it tries to access S3 storage and generates lot of exception log messages. For now, we should turn off scheduled refresh of S3 metadata.

**Comment by horsburgh** [comment]
@pkdash - next major release is scheduled for end of July for the Platform. Is this something that needs to be done sooner than that, or should it get added to the milestone for that release?

**Comment by pkdash** [comment]
@horsburgh I have already got a PR for this. This does not need to be released/deployed now. If there are other minor issues in the meantime, we can plan for a minor release prior to the July milestone.
