### ISSUE TITLE
Clicking on the "contribute data" button takes users to the CZ Hub web page.

### ISSUE THREAD

**Issue by igarousi** [I-GUIDE/catalog#17]
To register a record to the data catalog, a user has two options:

1. Click on the "contribute data" button in the middle of the home page. This will redirect the user to the CZ Hub website. Please use the correct link. 
2. Click on the "contribute" button found on the top right toolbar. This will take the user directly to the IGUIDE data catalog submission page.

**Comment by Maurier** [comment]
Fixed
