### ISSUE TITLE
Temporal Coverage end date validation fails

### ISSUE THREAD

**Issue by Maurier** [I-GUIDE/catalog#60]
Error relates to overlap detection. 

![image](https://github.com/I-GUIDE/catalogapi/assets/2448568/22546d2f-8c4c-4f0c-89ff-f6ffefdac853)

**Comment by horsburgh** [comment]
@Maurier - is this complete?

**Comment by Maurier** [comment]
Not yet. I had a solution for this in the past that didn't fully work because of bugs in our dependencies and had to be discarded. I will try again now that we have updated the project to Vue 3.

**Comment by Maurier** [comment]
This has been fixed.
